name: Python CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: saifb/todo-app
  PYTHON_VERSION: "3.9"  # Set your Python version

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pylint (code analysis)
        run: |
          echo "Running pylint..."
          pylint --output-format=colorized --fail-under=7.0 ./  # Adjust path as needed
        continue-on-error: true  # Fail workflow if linting fails

      - name: Run flake8 (style checking)
        run: |
          echo "Running flake8..."
          flake8 --count --show-source --statistics ./  # Adjust path as needed
        continue-on-error: true

  trivy-scan:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          exit-code: '1'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          skip-dirs: '__pycache__,venv,.git'

  build-and-push:
    runs-on: ubuntu-latest
    needs: trivy-scan
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          load: true

      - name: Scan Docker image with Trivy
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --exit-code 1 \
            --severity CRITICAL,HIGH \
            --ignore-unfixed \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest